### PR TITLE
Add test case: Spec with fields that are not used in the chart

### PR DESCRIPTION
**Pull request by pezhang**
1. Add test case, test expectation
2. Add test case ID (Polarion  test case ID) to test suit
3. More info about the code logic: Set HelmRelease with fields that are not used in the chart "unused: unused", the checkpoint is the chart still can be deployed successfully with it's default value.

### CODE REVIEW

**Comment by pezhang** [comment]
@ianzhang366 Could you help to review this patch? Thanks a lot.

**Comment by ianzhang366** [comment]
@pezhang great work, also, we move all the tests to the github action, if you want to see what's going on pay attention to github actions' status.

**Comment by pezhang** [comment]
@ianzhang366 Thanks for your review and comments.

**Pull request merged**
